project_id = "dagoajsdjumdcmvmedew"

[functions.generate-workout]
verify_jwt = true

[functions.replace-exercise]
verify_jwt = true

[functions.n8n-chat]
verify_jwt = true

[functions.generate-stretching]
verify_jwt = true

[functions.upload-exercise-image]
verify_jwt = true

[functions.ai-chat]
verify_jwt = false

[functions.generate-exercise-images]
verify_jwt = false